### ISSUE TITLE
Missing schema/apartment.sql

### ISSUE THREAD

**Issue by manoj97738** [mcsekar12/Apartment-Management#1]
I was trying to go through your code for apartment management but could not find 
schema/apartment.sql could you provide one?

**Comment by kunal4687** [comment]
how do I get schema/apartment.sql? PLease help.

**Comment by mcsekar12** [comment]
please find the schema in the  [link](https://drive.google.com/file/d/0B_s4sqapbdavVU14aTY1NkNaQ014dXFEU3ZtblpRTEdtbW00/view?usp=sharing)

**Comment by kunal4687** [comment]
Dear Sir,
Thank you for your response but the LINK is not working.
Please help .
